### ISSUE TITLE
engine file missing

### ISSUE THREAD

**Issue by ctf0** [phpfmt/issues#10]
Description:
![screen shot 2016-06-11 at 8 06 49 am](https://cloud.githubusercontent.com/assets/7388088/15983547/8c77bc36-2fab-11e6-9856-50345841e07c.png)

dont know what else to add.

Your configuration:
```json
{
    "debug": false,
    "enable_auto_align": true,
    "excludes": [
        "PrettyPrintDocBlocks"
    ],
    "format_on_save": false,
    "passes": [
        "AlignDoubleArrow",
        "AlignDoubleSlashComments",
        "AlignPHPCode",
        "AlignEquals",
        "AutoSemicolon",
        "IndentTernaryConditions",
        "MergeElseIf",
        "PrettyPrintDocBlocks",
        "ReturnNull",
        "ReindentSwitchBlocks",
        "ReindentAndAlignObjOps",
        "ShortArray",
        "StripNewlineAfterClassOpen",
        "StripNewlineAfterCurlyOpen",
        "StripExtraCommaInArray",
        "SmartLnAfterCurlyOpen",
        "RemoveUseLeadingSlash",
        "ReindentSwitchBlocks",
        "RemoveSemicolonAfterCurly",
        "SpaceBetweenMethods",
        "OrderAndRemoveUseClauses"
    ],
    "psr2": true,
    "version": 1,
    "visibility_order": true
}
```

phpfmt engine channel and branch:
```
803.7.0
```

**Comment by balthild** [comment]
Same issue on windows version.

**Comment by zoic21** [comment]
Same issue on windows

**Comment by jankoehoorn** [comment]
Same here, on Sublime Text 3, OSX El Capitan

![image](https://cloud.githubusercontent.com/assets/3000450/15984437/ef46694c-2fca-11e6-9435-8badea032202.png)

`{
	"enable_auto_align": true,
	"format_on_save": false,
	"passes":
	[
		"ReindentSwitchBlocks"
	],
	"php55warning": true,
	"php_bin": "/Applications/MAMP/bin/php/php7.0.0/bin/php",
	"psr1_naming": false,
	"psr2": true,
	"version": 4,
	"yoda": true
}
`

**Comment by ccirello** [comment]
Please, download php-cs-fixer and place it in the plugin directory and the error message will be gone.

**Comment by ccirello** [comment]
@ctf0 I see you are using a fmt.phar centric configuration. Be sure to buy a fmt.phar license to keep using it.
