### ISSUE TITLE
engine error

### ISSUE THREAD

**Issue by mars19850703** [phpfmt/issues#15]
My config is
{
"engine": "php-cs-fixer",
"enable_auto_align": true,
"indent_with_space": false,
"psr2": true,
"version": 4,
"php_bin":"/usr/local/php5/bin/php",
"format_on_save": false,
"options": ["fix","-n"]
}

but it show me
engine file is missing: /Users/mars/Library/Application Support/Sublime Text 3/Packages/phpfmt/php-cs-fixer

**Comment by tronghiep92** [comment]
Today, me too.

**Comment by kokororin** [comment]
```
composer global require "friendsofphp/php-cs-fixer"
```
and then set "engine" to `~/.composer/vendor/bin/php-cs-fixer`

**Comment by in-asif-mulla** [comment]
Using composer method it solved engine error issue, but unable to auto-indent or auto-alignment now.
