### ISSUE TITLE
Auto align doesn't work

### ISSUE THREAD

**Issue by Sotiris-k** [phpfmt/issues#18]
Description:
```
enable_auto_align doesn't work
```

Failing code:
```
array ( 
   'key1' => 'value1',
   'key23232' => 'valueblahblah'
);
```

Expected result:
```
array ( 
   'key1'     => 'value1',
   'key23232' => 'valueblahblah'
);
```

Actual result:
```
<insert the actual result>
```

Your configuration:
```
{
"version": 4,
"engine": "php-cs-fixer",
"options": ["fix","-n"],
"enable_auto_align" : true,
"format_on_save" : true
}

```

phpfmt engine channel and branch:
```
php-cs-fixer
```

**Comment by ccirello** [comment]
This is a php-cs-fixer issue. You need to check its documentation to see if they support it. However, you can have the auto-alignment back if you purchase a fmt.phar license. Good luck with php-cs-fixer.
