### ISSUE TITLE
how to disable phpfmt's autoupdate? i want to use the older version.

### ISSUE THREAD

**Issue by kenw2004** [phpfmt/issues#20]
Phpfmt is very convenient,I used it all the time,but i can not use the newest version(just 3hours ago).

The newest version broken my code when save and format, so my code can not work at php 5.3 on server. 

The reason is that it modified the array of formatting rules.

PHP7: $a = [];
php5: $a = array();
php5 can not support $a = [];

How to disable phpfmt's autoupdate? i want to use the older version.

**Comment by ccirello** [comment]
You can purchase a license of fmt.phar that addresses this problem for you. Refer to #17

**Comment by ccirello** [comment]
@kenw2004 more importantly, fmt.phar is commercial software. If you are using it in commercial settings, even the alpha channel is paid.
