### ISSUE TITLE
Not sure what happened with phpfmt

### ISSUE THREAD

**Issue by nanch** [phpfmt/issues#21]
I may be mistaken, but it seems like you switched this from a "free" business to a "paid" business without letting people know what's going on.

I understand that you want to get paid and I'd be happy to purchase a license from you for fmt.phar, but you don't have any public pricing available and you've surprised me with this "upgrade".

Could you let us know what you're planning, why you're planning it, and provide some insight into what your thinking is?

As of now I'm forking and reverting to a previous version. I hope you can provide some guidance because I'd like to support you and I enjoy using phpfmt.

Thank you.

**Comment by ccirello** [comment]
Be sure to buy a license when you do it.

**Comment by ccirello** [comment]
#17 is relevant to your case.

**Comment by ccirello** [comment]
> I hope you can provide some guidance because I'd like to support you and I enjoy using phpfmt.

Thanks, I appreciate your contact. The best line of action is to delete your fork to avoid a DMCA take down notice for the phar files, contact me through email so I can arrange a license for you.
